import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated service worker bundle (minified build artifact).
    "public/sw.js",
    // Prisma Client, regenerated by `prisma generate` on every install. Linting
    // machine-written code produces hundreds of findings nobody can act on and
    // buries the ones in code we actually wrote.
    "src/generated/**",
  ]),
]);

export default eslintConfig;
